//
//  ShopDetail.swift
//  TATapp
//
//  Created by Waleerat Gottlieb on 2023-04-04.
//

import Foundation
/*
let shopDetail = AccommodationDetailModel(result: AccommodationDetail(placeId: "P02000001", placeName: "อมารี ดอนเมือง แอร์พอร์ต กรุงเทพ", latitude: 13.920694, longitude: 100.600622, sha: SHA(shaName: "อมารี ดอนเมือง แอร์พอร์ต กรุงเทพฯ", shaTypeCode: "2", shaTypeDescription: "โรงแรมและที่พัก สถานที่จัดการประชุม", shaCateId: "3", shaCateDescription: "SHA Extra+"), placeInformation: Accommodation(introduction: "ด้วยห้องพักเหนือระดับ พร้อมกับภัตตาคารมากมายและสิ่งอำนวยความสะดวกทางธุรกิจชั้นยอด ทำให้โรงแรมอมารี ดอนเมืองเป็นตัวเลือกยอดนิยมของทั้งนักธุรกิจและนักท่องเที่ยว โดยห้องพักที่ได้รับการตกแต่งอย่างดี 423 ห้องเพียบพร้อมไปด้วยความสะดวกสบาย ขณะที่ภัตตาคารในโรงแรมก็เหมาะสำหรับใช้จัดงานทุกชนิด ตั้งแต่ปาร์ตี้ส่วนตัวไปจนถึงงานฉลองสุดอลังการ", detail: "ด้วยห้องพักเหนือระดับ พร้อมกับภัตตาคารมากมายและสิ่งอำนวยความสะดวกทางธุรกิจชั้นยอด ทำให้โรงแรมอมารี ดอนเมืองเป็นตัวเลือกยอดนิยมของทั้งนักธุรกิจและนักท่องเที่ยว โดยห้องพักที่ได้รับการตกแต่งอย่างดี 423 ห้องเพียบพร้อมไปด้วยความสะดวกสบาย ขณะที่ภัตตาคารในโรงแรมก็เหมาะสำหรับใช้จัดงานทุกชนิด ตั้งแต่ปาร์ตี้ส่วนตัวไปจนถึงงานฉลองสุดอลังการ", accommodationTypes: [AccommodationType(code: "18", description: "โรงแรมที่จดทะเบียน")], registerLicenseID: "มทท.202-003-590015-3", hotelStar: "4", displayCheckinTime: "15:00", displayCheckoutTime: "12:00", numberOfRooms: 423, priceRange: "2000 - 4500"), location: Location(address: "333 ถนนเชิดวุฒิกาศ", subDistrict: "ดอนเมือง", district: "ดอนเมือง", province: "กรุงเทพมหานคร", postcode: "10210"), contact: Contact(phones: ["02-566-1020"], mobiles: nil, fax: Optional("02-566-1941"), emails: Optional(["reservations@airport.amari.com"]), urls: Optional(["www.amari.com/donmuang"])), thumbnailUrl: "https://tatapi.tourismthailand.org/tatfs/Image/custompoi/Thumbnail/P02000001.jpg", webPictureUrls: ["https://tatapi.tourismthailand.org/tatfs/Image/custompoi/picture/P02000001_1.jpg", "https://tatapi.tourismthailand.org/tatfs/Image/custompoi/picture/P02000001_2.jpg", "https://tatapi.tourismthailand.org/tatfs/Image/custompoi/picture/P02000001_3.jpg", "https://tatapi.tourismthailand.org/tatfs/Image/custompoi/picture/P02000001_4.jpg", "https://tatapi.tourismthailand.org/tatfs/Image/custompoi/picture/P02000001_5.jpg"], mobilePictureUrls: ["https://tatapi.tourismthailand.org/tatfs/Image/CustomPOI/PictureMob/P02000001_1.jpeg"], facilities: [Facility(code: "PK", description: "ที่จอดรถ")], services: nil, paymentMethods: [PaymentMethod(code: "CR", description: "บัตรเครดิต"), PaymentMethod(code: "CS", description: "เงินสด")], howToTravel: "", destination: "กรุงเทพมหานคร", tags: nil, standard: "มาตรฐานที่พักเพื่อการท่องเที่ยวประเภทโรงแรม ระดับ 1-4 ดาว", awards: [""], updateDate: "2020-01-13T14:51:01.173", rooms: nil, hitScore: nil))*/

